config/routes.rb
Rails.application.routes.draw do
  
  
  root 'pages#home'
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/article.rb
class Article <ActiveRecord::Base
    belongs_to :user
    validates :score, presence: true
    validates :user_id, presence: true
    validates :user_linemanager, presence: true
    #validates :comment
    #validates :user_id, presence: true
    
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    before_save {self.email = email.downcase }
    validates :username, presence:true, length: {minimum:3, maximum:25}, 
                uniqueness: {case_sensitive: false}
    
    validates :linemanager, presence:true
    
    VALID_EMAIL_REGEX= /([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4})/i
    validates :email, presence: true, length: {maximum: 105},
                uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX }
    
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def current_linemanager
     @current_linemanager ||= User.find(session[:user_id]).linemanager if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_user
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    def index
        @articles = Article.order('created_at DESC').paginate(page: params[:page], per_page: 10)
    end
    
    def new
        @article = Article.new
    end
    
    def create
        @article = Article.new(article_params)
        @article.user = current_user
        
        @article.user_linemanager = current_linemanager
        if @article.save
            flash[:success] = "Score has been submitted"
            redirect_to article_path(@article)
        else
            render 'new'
        end
        
    end
    
    def show
        
    end
    
    def destroy
        
        @article.destroy
        flash[:danger] = "Score has been deleted"
        redirect_to user_path(@article.user)
    end
    
    def edit
        
    end
    
    def update
        
        if @article.update(article_params)
            flash[:success] = "Score was successfully submitted"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end
    
    private
    
    def set_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:score, :comment)
    end
    
    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:danger] = "You can only edit or delete your own articles"
            redirect_to root_path
        end
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        redirect_to users_path if logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    
    end
    
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            session[:user_linemanager] = user.linemanager
            
            flash[:success] = "You have successfully logged in"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "There was something wrong with your login information"
            render 'new'
        end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only:[:destroy]
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Welcome to the WSP App #{@user.username}"
            redirect_to users_path
        else
            render 'new'
        end
    end
    
    def edit
        
    end
    
    def update
        
        if @user.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to users_path
        else
            render 'edit'
        end
    end
    
    def show
       
       @user_articles = @user.articles.order('created_at DESC').paginate(page: params[:page], per_page: 5)
       @articlesuserid = @user.articles.first
      @result = {}
        @user.articles.each do |u|
        @result[u.created_at] = u.score
        end
    end
    
    def destroy
       @user = User.find(params[:id])
       @user.destroy
       flash[:danger] = "User and all scores created by user have been deleted"
       redirect_to users_path
    end
    
    def index
        if logged_in? && current_user.admin?
            @users = User.paginate(page: params[:page], per_page: 10)
        else
            @users = User.all
        end
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password, :linemanager)
    end
    
    def require_same_user
        if !logged_in? || current_user != @user && !current_user.admin?
            flash[:danger] = "You can only edit your own account"
            redirect_to root_path
        end
    end
    
    def set_user
        @user = User.find(params[:id])
    end
    
    def require_admin
        if logged_in? && !current_user.admin?
            flash[:danger] = "Only admin users can perform that action"
            redirect_to root_path
        end
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<table class="table table-hover">
    <tr>
        <th>Score</th>
        <th>Comment</th>
        <th>Created At:</th>
        <th>Created by:</th>
         
    </tr>
    
    <% obj.each do |a| %>
        <tr>
            <td>
                <%= a.score %>
            </td>
            <td>
                <%= a.comment %>
            </td>
            <td>
                <%= time_ago_in_words(a.created_at) %> ago
            </td>
            <td>
                <%= a.user.username %>
            </td>
            <td><%= link_to "Show", article_path(a) %></td>
            <% if logged_in? && (current_user == a.user || current_user.admin?) %>
                <td><%= link_to "Edit", edit_article_path(a) %></td>
                
                <td><%= link_to "Delete", article_path(a), method: :delete, data: {confirm: "Are you sure?"} %></td>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
    <div class='col-xs-12'>
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <!--<div class="form-group">-->
            <!--    <div class="control-label col-sm-2">-->
                    <%#= f.label :score %>
            <!--    </div>-->
            <!--    <div class="col-sm-8">-->
                    <%#= f.number_field :score, class: "form-control", placeholder: "Input your score", autofocus: true %>
            <!--    </div>-->
            <!--</div>-->
            
            <div class="form-group center">
               
                    <label><input type="radio" name="article[score]" value="1" id="radio1"><%= image_tag 'WSP Health App/bad.png' %></label> 
                    <label><input type="radio" name="article[score]" value="2" id="radio2"><%= image_tag 'WSP Health App/soso.png' %></label> 
                    <label><input type="radio" name="article[score]" value="3" id="radio3"><%= image_tag 'WSP Health App/fair.png' %></label>
                    <label><input type="radio" name="article[score]" value="4" id="radio4"><%= image_tag 'WSP Health App/okay.png' %></label>
                    <label><input type="radio" name="article[score]" value="5" id="radio5"><%= image_tag 'WSP Health App/happy.png' %></label>
                
            </div>
            
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :comment %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_area :comment, rows: 5, class: "form-control", placeholder: "Comments(Optional)", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                <%= link_to "Back", articles_path, class:"btn btn-danger" %>
                <%= f.submit "Submit Score", class: 'btn btn-primary' %>
                </div>
            </div>

        
        <% end %>
        
        
        
        
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit Score</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<% if logged_in? && current_user.admin? %>
<h1>Listing all Scores</h1>
<div align="center">
    <%= will_paginate %>
</div>

    <%= render 'article', obj: @articles  %>

<div align="center">
    <%= will_paginate %>
</div>
<% else %>
<h1 align = "center">You have no right to access this page.</h1>
<% end %>

app/views/articles/new.html.erb
<h1 align="center">New Score</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<% if logged_in? && (current_user == @article.user || current_user.id.to_s == @article.user_linemanager || current_user.admin?) %>
<h2 align="center">Score: <%= @article.score %></h2>
<div class="well col-xs-8 col-xs-offset-2">
    <h4 class="center description"><strong>Comment:</strong></h4>
    <hr>
    <%= simple_format(@article.comment) %>
        <div class"article-actions">
            <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
                <%#= link_to "Back", articles_path, class: "btn btn-danger" %>
                <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-success" %>
                <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
            <% end %>
        </div>
</div>
<% else %>
    <h1 align="center">You have no right to see this content</h1>
<% end %>


 
    

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; <a href="http://www.wsp-pb.com/en/WSP-UK/?_ga=2.176732131.735298241.1504125720-2037321440.1504125720">WSP Health App</a>
            by <a href="https://www.linkedin.com/in/kelvin-sc-yeung-13885839/">Kelvin Yeung</a>
        </small>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "WSP", root_path, class: "navbar-brand", id:"logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <% if logged_in? && current_user.admin? %>
        <li><%= link_to "All Existing Scores", articles_path %></li>
        <% end %>
        <% if logged_in? %>
          <li><%= link_to "Your Reportees", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Scores", new_article_path %></li>
              <li><a href="#">Health and Wellbeing Webpage (under construction)</a></li>
              <li><a href="#">Safety Facts (under construction)</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Charity Events (under construction)</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Donations (under construction)</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <!--<form class="navbar-form navbar-left">-->
      <!--  <div class="form-group">-->
      <!--    <input type="text" class="form-control" placeholder="Search">-->
      <!--  </div>-->
      <!--  <button type="submit" class="btn btn-default">Submit</button>-->
      <!--</form>-->
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.admin? ? "Admin" : "Your Profile"  %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View your Profile", user_path(current_user) %></li>
              <% if logged_in? && current_user.admin? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Sign up New Users", signup_path %></li>
              <% end %>
            <% else %>
              <li><%= link_to 'Login', login_path %></li>
            <% end %>
            
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <%= javascript_include_tag 'application', 'Chart.bundle', 'chartkick','data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>
<div class="container">
<%= yield %>
</div>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
    <h1>Health & Wellbeing App</h1>

<%= link_to 'Login', login_path, class: "btn btn-danger btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibited the score form being submitted
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
    <div class='col-xs-12'>
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :username %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :username, class: "form-control", placeholder: "Enter name", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :email %>
                </div>
                <div class="col-sm-8">
                    <%= f.email_field :email, class: "form-control", placeholder: "Enter email", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :password %>
                </div>
                <div class="col-sm-8">
                    <%= f.password_field :password, class: "form-control", placeholder: "Enter password", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :linemanager %>
                </div>
                <div class="col-sm-8">
                    <%= f.number_field :linemanager, class: "form-control", placeholder: "Enter LineManager ID", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                <%= link_to "Back", articles_path, class:"btn btn-danger" %>
                <%= f.submit(@user.new_record? ? "Sign up" : "Update", class: 'btn btn-primary') %>
                </div>
            </div>

        
        <% end %>
        
    </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<% if logged_in? %>
    <h1 align="center">Your Reportees</h1>
    
    <% if logged_in? && current_user.admin? %>
    <div align="center">
        <%= will_paginate %>
    </div>
    <% end %>
    <table class="table table-hover">
        <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Users ID</th>
            <th>Line Manager ID</th>
            <th>Latest Score</th>
            <th>Last Updated</th>
            <% if logged_in? && current_user.admin? %>
                <th>Admin?</th>
                <th>Delete User</th>
            <% end %>
        </tr>
        <% @users.each do |u| %>
            <% if logged_in? && (current_user.id.to_s == u.linemanager || current_user.admin? )%>
            <tr>
                <td>
                    <%= link_to u.username, user_path(u) %>
                </td>
                <td>
                    <%= u.email %>
                </td>
                <td>
                    <%= u.id %>
                </td>
                <td>
                    <%= u.linemanager %>
                </td>
                <% if u.articles.last.nil? != true %>
                    <% if u.articles.last.score == "1" %>
                        <td>
                            <%= image_tag 'WSP Health App/bad.png' %>
                        </td>
                    <% elsif u.articles.last.score == "2" %>
                        <td>
                            <%= image_tag 'WSP Health App/soso.png' %>
                        </td>
                    <% elsif u.articles.last.score == "3" %>
                        <td>
                            <%= image_tag 'WSP Health App/fair.png' %>
                        </td>
                    <% elsif u.articles.last.score == "4" %>
                        <td>
                            <%= image_tag 'WSP Health App/okay.png' %>
                        </td>
                    <% elsif u.articles.last.score == "5" %>
                        <td>
                            <%= image_tag 'WSP Health App/happy.png' %>
                        </td>
                    <% end %>
                <% else %>
                <td>
                    N/A
                </td>
                <% end %>
                <% if u.articles.last.nil? != true %>
                <td>
                    <%= time_ago_in_words(u.articles.last.created_at) %> ago
                </td>
                <% else %>
                <td>
                    N/A
                </td>
                <% end %>
                <% if logged_in? && current_user.admin? %>
                <td>
                    <%= u.admin %>
                </td>
                        <td><%= link_to "Delete this user", user_path(u), method: :delete, 
                        data: { confirm: "Are you sure you want to delete the user and all their scores?"} %></td>
                <% end %>
            </tr>
            <% end %>
        <% end %>
    </table>
    
<% else %>
    <h1 align="center">You have no right to access this content</h1>
<% end %>

app/views/users/new.html.erb
<h1 align="center">User Signup</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<% if @articlesuserid.nil? != true %>
    <% if logged_in? && (current_user.id == @articlesuserid.user_id  || current_user.id.to_s == @articlesuserid.user_linemanager || current_user.admin?) %>
    <h1 align="center">Welcome to <%= @user.username %>'s page</h1>
    <div class="center">
        <%= will_paginate @user_articles %>
    </div>
    <%= render 'articles/article', obj: @user_articles %>
    <div class="center">
        <%= will_paginate @user_articles %>
    </div>
    <div>
    <h3>Scores</h3>
        <%= line_chart(@result, min: 0, max: 5, curve: false) %>
    </div>
    
    <% else %>
        <h1 align="center">You have no right to see this content</h1>
    <% end %>
<% else %>
    <h1 align="center">This User has no Scores submitted</h1>
<% end %>